export default {
    language: 'kr',
    name: '푸른 눈의 백룡',
    type: 'monster',
    attribute: 'light',
    image: require('@/assets/image/blue-eyes.jpg'),
    cardType: 'normal',
    level: 8,
    monsterType: '드래곤족 / 일반',
    atk: 3000,
    def: 2500,
    description: '높은 공격력을 자랑하는 전설의 드래곤. 어떠한 상대라도 분쇄해 버리는 파괴력은 상상을 초월한다.',
    firstLineCompress: false,
    package: 'SD25-KR001',
    password: '89631139',
    copyright: 'sc',
};
